title: Neil Patil
email: neilpatil215@gmail.com
tagline: Personal Website
description: Personal website. Software projects, blog posts, and contact info.
github_username:  patil215
logo: /img/favicon.jpg
author: neilpatil215
plugins:
  - jekyll-seo-tag
social:
  name: Neil Patil
  links:
    - https://twitter.com/neilpatil215
    - https://www.linkedin.com/in/patil215/
    - https://github.com/patil215

markdown: kramdown